#!/bin/bash
set -euo pipefail

# Reference: https://github.com/dtbaker/git-lfs-buildkite-plugin/blob/master/hooks/post-command

echo "--- Installing Git LFS v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}"

# Install Git LFS
mkdir -p .gitlfs/
rm -rf .gitlfs/git-lfs*
export PATH=$PATH:.gitlfs/

curl -Lsf -o git-lfs.tgz https://github.com/git-lfs/git-lfs/releases/download/v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/git-lfs-linux-amd64-v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}.tar.gz
tar -xvzf git-lfs.tgz
mv git-lfs-${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/git-lfs .gitlfs/git-lfs
rm -rf git-lfs.tgz git-lfs-${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/

git lfs install

echo "--- Git LFS v${BUILDKITE_PLUGIN_GIT_LFS_VERSION} installed successfully"
