#!/bin/bash
set -euo pipefail

# Reference: https://github.com/dtbaker/git-lfs-buildkite-plugin/blob/master/hooks/post-command

echo "--- Installing Git LFS v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}"

# Install Git LFS
curl -Lsf -o git-lfs.tgz https://github.com/git-lfs/git-lfs/releases/download/v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/git-lfs-linux-amd64-v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}.tar.gz
tar -xvzf git-lfs.tgz
./git-lfs-${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/install.sh
rm -rf git-lfs.tgz git-lfs-${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/

# https://github.com/git-lfs/git-lfs/issues/2291#issuecomment-305887405
rm .git/hooks/pre-push

echo "--- Git LFS v${BUILDKITE_PLUGIN_GIT_LFS_VERSION} installed successfully"
