#!/bin/bash
set -euo pipefail

# Reference: https://github.com/dtbaker/git-lfs-buildkite-plugin/blob/master/hooks/post-command

echo "--- Installing Git LFS v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}"

# Install Git LFS
curl -Lsf -o git-lfs.tgz https://github.com/git-lfs/git-lfs/releases/download/v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/git-lfs-linux-amd64-v${BUILDKITE_PLUGIN_GIT_LFS_VERSION}.tar.gz
tar -xvzf git-lfs.tgz
cp -a git-lfs-${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/git-lfs "$(git --exec-path)/git-lfs"
rm -rf git-lfs.tgz git-lfs-${BUILDKITE_PLUGIN_GIT_LFS_VERSION}/

git lfs install

# Double check if Git LFS is installed successfully
git lfs --version

echo "--- Git LFS v${BUILDKITE_PLUGIN_GIT_LFS_VERSION} installed successfully"
